/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReadyStockRouteImport } from './routes/_authenticated/ready-stock'
import { Route as AuthenticatedRatesRouteImport } from './routes/_authenticated/rates'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDraftsRouteImport } from './routes/_authenticated/drafts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedConsumptionRouteImport } from './routes/_authenticated/consumption'
import { Route as AuthenticatedCashbonRouteImport } from './routes/_authenticated/cashbon'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedOwnerSyncRouteImport } from './routes/_authenticated/owner.sync'
import { Route as AuthenticatedOwnerPricesRouteImport } from './routes/_authenticated/owner.prices'
import { Route as AuthenticatedOwnerExpensesRouteImport } from './routes/_authenticated/owner.expenses'
import { Route as AuthenticatedOwnerCarriersRouteImport } from './routes/_authenticated/owner.carriers'
import { Route as AuthenticatedOwnerAttendanceQrRouteImport } from './routes/_authenticated/owner.attendance-qr'
import { Route as AuthenticatedOwnerAttendanceHistoryRouteImport } from './routes/_authenticated/owner.attendance-history'
import { Route as AuthenticatedOwnerAnalyticsRouteImport } from './routes/_authenticated/owner.analytics'
import { Route as AuthenticatedMeShipRouteImport } from './routes/_authenticated/me.ship'
import { Route as AuthenticatedMeScanRouteImport } from './routes/_authenticated/me.scan'
import { Route as AuthenticatedMeRepairsRouteImport } from './routes/_authenticated/me.repairs'
import { Route as AuthenticatedMePickupRouteImport } from './routes/_authenticated/me.pickup'
import { Route as AuthenticatedMeJobsRouteImport } from './routes/_authenticated/me.jobs'
import { Route as AuthenticatedMeEarningsRouteImport } from './routes/_authenticated/me.earnings'
import { Route as AuthenticatedMeAttendanceRouteImport } from './routes/_authenticated/me.attendance'
import { Route as ApiPublicHooksSyncProjectsRouteImport } from './routes/api/public/hooks/sync-projects'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReadyStockRoute = AuthenticatedReadyStockRouteImport.update({
  id: '/ready-stock',
  path: '/ready-stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRatesRoute = AuthenticatedRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDraftsRoute = AuthenticatedDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsumptionRoute =
  AuthenticatedConsumptionRouteImport.update({
    id: '/consumption',
    path: '/consumption',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashbonRoute = AuthenticatedCashbonRouteImport.update({
  id: '/cashbon',
  path: '/cashbon',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerSyncRoute = AuthenticatedOwnerSyncRouteImport.update({
  id: '/owner/sync',
  path: '/owner/sync',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerPricesRoute =
  AuthenticatedOwnerPricesRouteImport.update({
    id: '/owner/prices',
    path: '/owner/prices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerExpensesRoute =
  AuthenticatedOwnerExpensesRouteImport.update({
    id: '/owner/expenses',
    path: '/owner/expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerCarriersRoute =
  AuthenticatedOwnerCarriersRouteImport.update({
    id: '/owner/carriers',
    path: '/owner/carriers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerAttendanceQrRoute =
  AuthenticatedOwnerAttendanceQrRouteImport.update({
    id: '/owner/attendance-qr',
    path: '/owner/attendance-qr',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerAttendanceHistoryRoute =
  AuthenticatedOwnerAttendanceHistoryRouteImport.update({
    id: '/owner/attendance-history',
    path: '/owner/attendance-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerAnalyticsRoute =
  AuthenticatedOwnerAnalyticsRouteImport.update({
    id: '/owner/analytics',
    path: '/owner/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeShipRoute = AuthenticatedMeShipRouteImport.update({
  id: '/me/ship',
  path: '/me/ship',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeScanRoute = AuthenticatedMeScanRouteImport.update({
  id: '/me/scan',
  path: '/me/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRepairsRoute = AuthenticatedMeRepairsRouteImport.update({
  id: '/me/repairs',
  path: '/me/repairs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMePickupRoute = AuthenticatedMePickupRouteImport.update({
  id: '/me/pickup',
  path: '/me/pickup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeJobsRoute = AuthenticatedMeJobsRouteImport.update({
  id: '/me/jobs',
  path: '/me/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeEarningsRoute = AuthenticatedMeEarningsRouteImport.update({
  id: '/me/earnings',
  path: '/me/earnings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeAttendanceRoute =
  AuthenticatedMeAttendanceRouteImport.update({
    id: '/me/attendance',
    path: '/me/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksSyncProjectsRoute =
  ApiPublicHooksSyncProjectsRouteImport.update({
    id: '/api/public/hooks/sync-projects',
    path: '/api/public/hooks/sync-projects',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/cashbon': typeof AuthenticatedCashbonRoute
  '/consumption': typeof AuthenticatedConsumptionRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/rates': typeof AuthenticatedRatesRoute
  '/ready-stock': typeof AuthenticatedReadyStockRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/me/attendance': typeof AuthenticatedMeAttendanceRoute
  '/me/earnings': typeof AuthenticatedMeEarningsRoute
  '/me/jobs': typeof AuthenticatedMeJobsRoute
  '/me/pickup': typeof AuthenticatedMePickupRoute
  '/me/repairs': typeof AuthenticatedMeRepairsRoute
  '/me/scan': typeof AuthenticatedMeScanRoute
  '/me/ship': typeof AuthenticatedMeShipRoute
  '/owner/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/owner/attendance-history': typeof AuthenticatedOwnerAttendanceHistoryRoute
  '/owner/attendance-qr': typeof AuthenticatedOwnerAttendanceQrRoute
  '/owner/carriers': typeof AuthenticatedOwnerCarriersRoute
  '/owner/expenses': typeof AuthenticatedOwnerExpensesRoute
  '/owner/prices': typeof AuthenticatedOwnerPricesRoute
  '/owner/sync': typeof AuthenticatedOwnerSyncRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/sync-projects': typeof ApiPublicHooksSyncProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/cashbon': typeof AuthenticatedCashbonRoute
  '/consumption': typeof AuthenticatedConsumptionRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/rates': typeof AuthenticatedRatesRoute
  '/ready-stock': typeof AuthenticatedReadyStockRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/me/attendance': typeof AuthenticatedMeAttendanceRoute
  '/me/earnings': typeof AuthenticatedMeEarningsRoute
  '/me/jobs': typeof AuthenticatedMeJobsRoute
  '/me/pickup': typeof AuthenticatedMePickupRoute
  '/me/repairs': typeof AuthenticatedMeRepairsRoute
  '/me/scan': typeof AuthenticatedMeScanRoute
  '/me/ship': typeof AuthenticatedMeShipRoute
  '/owner/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/owner/attendance-history': typeof AuthenticatedOwnerAttendanceHistoryRoute
  '/owner/attendance-qr': typeof AuthenticatedOwnerAttendanceQrRoute
  '/owner/carriers': typeof AuthenticatedOwnerCarriersRoute
  '/owner/expenses': typeof AuthenticatedOwnerExpensesRoute
  '/owner/prices': typeof AuthenticatedOwnerPricesRoute
  '/owner/sync': typeof AuthenticatedOwnerSyncRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/sync-projects': typeof ApiPublicHooksSyncProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/cashbon': typeof AuthenticatedCashbonRoute
  '/_authenticated/consumption': typeof AuthenticatedConsumptionRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drafts': typeof AuthenticatedDraftsRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/rates': typeof AuthenticatedRatesRoute
  '/_authenticated/ready-stock': typeof AuthenticatedReadyStockRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/me/attendance': typeof AuthenticatedMeAttendanceRoute
  '/_authenticated/me/earnings': typeof AuthenticatedMeEarningsRoute
  '/_authenticated/me/jobs': typeof AuthenticatedMeJobsRoute
  '/_authenticated/me/pickup': typeof AuthenticatedMePickupRoute
  '/_authenticated/me/repairs': typeof AuthenticatedMeRepairsRoute
  '/_authenticated/me/scan': typeof AuthenticatedMeScanRoute
  '/_authenticated/me/ship': typeof AuthenticatedMeShipRoute
  '/_authenticated/owner/analytics': typeof AuthenticatedOwnerAnalyticsRoute
  '/_authenticated/owner/attendance-history': typeof AuthenticatedOwnerAttendanceHistoryRoute
  '/_authenticated/owner/attendance-qr': typeof AuthenticatedOwnerAttendanceQrRoute
  '/_authenticated/owner/carriers': typeof AuthenticatedOwnerCarriersRoute
  '/_authenticated/owner/expenses': typeof AuthenticatedOwnerExpensesRoute
  '/_authenticated/owner/prices': typeof AuthenticatedOwnerPricesRoute
  '/_authenticated/owner/sync': typeof AuthenticatedOwnerSyncRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/sync-projects': typeof ApiPublicHooksSyncProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/approvals'
    | '/cashbon'
    | '/consumption'
    | '/customers'
    | '/dashboard'
    | '/drafts'
    | '/employees'
    | '/orders'
    | '/payroll'
    | '/rates'
    | '/ready-stock'
    | '/reports'
    | '/users'
    | '/me/attendance'
    | '/me/earnings'
    | '/me/jobs'
    | '/me/pickup'
    | '/me/repairs'
    | '/me/scan'
    | '/me/ship'
    | '/owner/analytics'
    | '/owner/attendance-history'
    | '/owner/attendance-qr'
    | '/owner/carriers'
    | '/owner/expenses'
    | '/owner/prices'
    | '/owner/sync'
    | '/projects/$id'
    | '/projects/'
    | '/api/public/hooks/sync-projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/approvals'
    | '/cashbon'
    | '/consumption'
    | '/customers'
    | '/dashboard'
    | '/drafts'
    | '/employees'
    | '/orders'
    | '/payroll'
    | '/rates'
    | '/ready-stock'
    | '/reports'
    | '/users'
    | '/me/attendance'
    | '/me/earnings'
    | '/me/jobs'
    | '/me/pickup'
    | '/me/repairs'
    | '/me/scan'
    | '/me/ship'
    | '/owner/analytics'
    | '/owner/attendance-history'
    | '/owner/attendance-qr'
    | '/owner/carriers'
    | '/owner/expenses'
    | '/owner/prices'
    | '/owner/sync'
    | '/projects/$id'
    | '/projects'
    | '/api/public/hooks/sync-projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/approvals'
    | '/_authenticated/cashbon'
    | '/_authenticated/consumption'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/drafts'
    | '/_authenticated/employees'
    | '/_authenticated/orders'
    | '/_authenticated/payroll'
    | '/_authenticated/rates'
    | '/_authenticated/ready-stock'
    | '/_authenticated/reports'
    | '/_authenticated/users'
    | '/_authenticated/me/attendance'
    | '/_authenticated/me/earnings'
    | '/_authenticated/me/jobs'
    | '/_authenticated/me/pickup'
    | '/_authenticated/me/repairs'
    | '/_authenticated/me/scan'
    | '/_authenticated/me/ship'
    | '/_authenticated/owner/analytics'
    | '/_authenticated/owner/attendance-history'
    | '/_authenticated/owner/attendance-qr'
    | '/_authenticated/owner/carriers'
    | '/_authenticated/owner/expenses'
    | '/_authenticated/owner/prices'
    | '/_authenticated/owner/sync'
    | '/_authenticated/projects/$id'
    | '/_authenticated/projects/'
    | '/api/public/hooks/sync-projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksSyncProjectsRoute: typeof ApiPublicHooksSyncProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ready-stock': {
      id: '/_authenticated/ready-stock'
      path: '/ready-stock'
      fullPath: '/ready-stock'
      preLoaderRoute: typeof AuthenticatedReadyStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rates': {
      id: '/_authenticated/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof AuthenticatedRatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drafts': {
      id: '/_authenticated/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AuthenticatedDraftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consumption': {
      id: '/_authenticated/consumption'
      path: '/consumption'
      fullPath: '/consumption'
      preLoaderRoute: typeof AuthenticatedConsumptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashbon': {
      id: '/_authenticated/cashbon'
      path: '/cashbon'
      fullPath: '/cashbon'
      preLoaderRoute: typeof AuthenticatedCashbonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/sync': {
      id: '/_authenticated/owner/sync'
      path: '/owner/sync'
      fullPath: '/owner/sync'
      preLoaderRoute: typeof AuthenticatedOwnerSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/prices': {
      id: '/_authenticated/owner/prices'
      path: '/owner/prices'
      fullPath: '/owner/prices'
      preLoaderRoute: typeof AuthenticatedOwnerPricesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/expenses': {
      id: '/_authenticated/owner/expenses'
      path: '/owner/expenses'
      fullPath: '/owner/expenses'
      preLoaderRoute: typeof AuthenticatedOwnerExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/carriers': {
      id: '/_authenticated/owner/carriers'
      path: '/owner/carriers'
      fullPath: '/owner/carriers'
      preLoaderRoute: typeof AuthenticatedOwnerCarriersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/attendance-qr': {
      id: '/_authenticated/owner/attendance-qr'
      path: '/owner/attendance-qr'
      fullPath: '/owner/attendance-qr'
      preLoaderRoute: typeof AuthenticatedOwnerAttendanceQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/attendance-history': {
      id: '/_authenticated/owner/attendance-history'
      path: '/owner/attendance-history'
      fullPath: '/owner/attendance-history'
      preLoaderRoute: typeof AuthenticatedOwnerAttendanceHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/analytics': {
      id: '/_authenticated/owner/analytics'
      path: '/owner/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof AuthenticatedOwnerAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/ship': {
      id: '/_authenticated/me/ship'
      path: '/me/ship'
      fullPath: '/me/ship'
      preLoaderRoute: typeof AuthenticatedMeShipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/scan': {
      id: '/_authenticated/me/scan'
      path: '/me/scan'
      fullPath: '/me/scan'
      preLoaderRoute: typeof AuthenticatedMeScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/repairs': {
      id: '/_authenticated/me/repairs'
      path: '/me/repairs'
      fullPath: '/me/repairs'
      preLoaderRoute: typeof AuthenticatedMeRepairsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/pickup': {
      id: '/_authenticated/me/pickup'
      path: '/me/pickup'
      fullPath: '/me/pickup'
      preLoaderRoute: typeof AuthenticatedMePickupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/jobs': {
      id: '/_authenticated/me/jobs'
      path: '/me/jobs'
      fullPath: '/me/jobs'
      preLoaderRoute: typeof AuthenticatedMeJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/earnings': {
      id: '/_authenticated/me/earnings'
      path: '/me/earnings'
      fullPath: '/me/earnings'
      preLoaderRoute: typeof AuthenticatedMeEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me/attendance': {
      id: '/_authenticated/me/attendance'
      path: '/me/attendance'
      fullPath: '/me/attendance'
      preLoaderRoute: typeof AuthenticatedMeAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/sync-projects': {
      id: '/api/public/hooks/sync-projects'
      path: '/api/public/hooks/sync-projects'
      fullPath: '/api/public/hooks/sync-projects'
      preLoaderRoute: typeof ApiPublicHooksSyncProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedCashbonRoute: typeof AuthenticatedCashbonRoute
  AuthenticatedConsumptionRoute: typeof AuthenticatedConsumptionRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDraftsRoute: typeof AuthenticatedDraftsRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedRatesRoute: typeof AuthenticatedRatesRoute
  AuthenticatedReadyStockRoute: typeof AuthenticatedReadyStockRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedMeAttendanceRoute: typeof AuthenticatedMeAttendanceRoute
  AuthenticatedMeEarningsRoute: typeof AuthenticatedMeEarningsRoute
  AuthenticatedMeJobsRoute: typeof AuthenticatedMeJobsRoute
  AuthenticatedMePickupRoute: typeof AuthenticatedMePickupRoute
  AuthenticatedMeRepairsRoute: typeof AuthenticatedMeRepairsRoute
  AuthenticatedMeScanRoute: typeof AuthenticatedMeScanRoute
  AuthenticatedMeShipRoute: typeof AuthenticatedMeShipRoute
  AuthenticatedOwnerAnalyticsRoute: typeof AuthenticatedOwnerAnalyticsRoute
  AuthenticatedOwnerAttendanceHistoryRoute: typeof AuthenticatedOwnerAttendanceHistoryRoute
  AuthenticatedOwnerAttendanceQrRoute: typeof AuthenticatedOwnerAttendanceQrRoute
  AuthenticatedOwnerCarriersRoute: typeof AuthenticatedOwnerCarriersRoute
  AuthenticatedOwnerExpensesRoute: typeof AuthenticatedOwnerExpensesRoute
  AuthenticatedOwnerPricesRoute: typeof AuthenticatedOwnerPricesRoute
  AuthenticatedOwnerSyncRoute: typeof AuthenticatedOwnerSyncRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedCashbonRoute: AuthenticatedCashbonRoute,
  AuthenticatedConsumptionRoute: AuthenticatedConsumptionRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDraftsRoute: AuthenticatedDraftsRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedRatesRoute: AuthenticatedRatesRoute,
  AuthenticatedReadyStockRoute: AuthenticatedReadyStockRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedMeAttendanceRoute: AuthenticatedMeAttendanceRoute,
  AuthenticatedMeEarningsRoute: AuthenticatedMeEarningsRoute,
  AuthenticatedMeJobsRoute: AuthenticatedMeJobsRoute,
  AuthenticatedMePickupRoute: AuthenticatedMePickupRoute,
  AuthenticatedMeRepairsRoute: AuthenticatedMeRepairsRoute,
  AuthenticatedMeScanRoute: AuthenticatedMeScanRoute,
  AuthenticatedMeShipRoute: AuthenticatedMeShipRoute,
  AuthenticatedOwnerAnalyticsRoute: AuthenticatedOwnerAnalyticsRoute,
  AuthenticatedOwnerAttendanceHistoryRoute:
    AuthenticatedOwnerAttendanceHistoryRoute,
  AuthenticatedOwnerAttendanceQrRoute: AuthenticatedOwnerAttendanceQrRoute,
  AuthenticatedOwnerCarriersRoute: AuthenticatedOwnerCarriersRoute,
  AuthenticatedOwnerExpensesRoute: AuthenticatedOwnerExpensesRoute,
  AuthenticatedOwnerPricesRoute: AuthenticatedOwnerPricesRoute,
  AuthenticatedOwnerSyncRoute: AuthenticatedOwnerSyncRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksSyncProjectsRoute: ApiPublicHooksSyncProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
